/**
 * Emoji động Noto (Google, CC BY 4.0) — spec visuals-3 A1. File Lottie tải một
 * lần bằng `apps/web/scripts/fetch-noto-emoji.mts` vào `packages/clip-media/lottie/emoji/`,
 * gọi bằng `builtin:emoji/<tên>`. Danh mục ở ĐÂY (thuần) để op, agent và bảng
 * Visuals biết tên mà không đọc file; script đọc danh mục này để tải.
 *
 * Chọn cho clip nói chuyện: cảm xúc, phản ứng, tay, tim, ý tưởng, tiền, thời
 * gian, thành công/thất bại. Không lấy cờ, người có tông da, đồ ăn lặt vặt.
 * Chỉ giữ emoji Noto có bản động (tải 404 thì bỏ), bỏ vài file >250 KB ít dùng
 * để cả bộ dưới ~10 MB (Modal và trình duyệt tải theo nhu cầu, từng file).
 */

import type { LottieEntry } from './lottie';

export type EmojiEntry = LottieEntry & { codepoint: string; emoji: string };

const e = (name: string, codepoint: string, title: string, tags: string[]): EmojiEntry => ({
	name: `emoji/${name}`,
	codepoint,
	emoji: String.fromCodePoint(...codepoint.split('_').map((part) => parseInt(part, 16))),
	title,
	tags: ['emoji', ...tags],
});

export const EMOJI_PACK: EmojiEntry[] = [
	// Mặt: vui
	e('grinning', '1f600', 'Grinning face', ['happy', 'smile', 'joy', 'good']),
	e('joy', '1f602', 'Tears of joy', ['laugh', 'funny', 'lol', 'haha', 'joke']),
	e('rofl', '1f923', 'Rolling on the floor laughing', ['laugh', 'funny', 'lol', 'hilarious']),
	e('smile', '1f60a', 'Smiling face', ['happy', 'smile', 'warm', 'kind']),
	e('wink', '1f609', 'Winking face', ['wink', 'joke', 'secret', 'playful']),
	e('heart-eyes', '1f60d', 'Heart eyes', ['love', 'adore', 'amazing', 'wow', 'beautiful']),
	e('star-struck', '1f929', 'Star-struck', ['wow', 'amazing', 'excited', 'fan', 'famous']),
	e('partying', '1f973', 'Partying face', ['party', 'celebrate', 'birthday', 'win', 'launch']),
	e('sunglasses', '1f60e', 'Cool face', ['cool', 'confident', 'boss', 'chill']),
	e('hugging', '1f917', 'Hugging face', ['hug', 'thanks', 'welcome', 'love']),
	e('relieved', '1f60c', 'Relieved face', ['calm', 'relief', 'peace', 'relax']),
	e('upside-down', '1f643', 'Upside-down face', ['irony', 'silly', 'sarcasm', 'awkward']),
	e('money-mouth', '1f911', 'Money-mouth face', ['money', 'rich', 'profit', 'greedy', 'cash']),
	e('yum', '1f60b', 'Yummy face', ['tasty', 'delicious', 'food', 'yum']),
	e('innocent', '1f607', 'Innocent face', ['angel', 'innocent', 'good', 'pure']),
	// Mặt: nghĩ, ngạc nhiên
	e('thinking', '1f914', 'Thinking face', ['think', 'question', 'hmm', 'wonder', 'idea', 'why']),
	e('monocle', '1f9d0', 'Face with monocle', ['inspect', 'curious', 'analyze', 'detail', 'research']),
	e('raised-eyebrow', '1f928', 'Raised eyebrow', ['doubt', 'suspicious', 'skeptical', 'really']),
	e('shushing', '1f92b', 'Shushing face', ['secret', 'quiet', 'shh', 'hidden']),
	e('zipper-mouth', '1f910', 'Zipper-mouth face', ['secret', 'silent', 'no comment']),
	e('open-mouth', '1f62e', 'Surprised face', ['surprise', 'wow', 'oh', 'shock']),
	e('astonished', '1f632', 'Astonished face', ['shock', 'surprise', 'wow', 'unbelievable']),
	e('exploding-head', '1f92f', 'Mind blown', ['mind blown', 'shock', 'wow', 'crazy', 'insight']),
	e('flushed', '1f633', 'Flushed face', ['embarrassed', 'shy', 'awkward', 'oops']),
	e('eyes', '1f440', 'Eyes', ['look', 'watch', 'see', 'attention', 'notice']),
	e('rolling-eyes', '1f644', 'Rolling eyes', ['annoyed', 'whatever', 'bored', 'eye roll']),
	e('neutral', '1f610', 'Neutral face', ['meh', 'neutral', 'blank']),
	e('expressionless', '1f611', 'Expressionless face', ['meh', 'unimpressed', 'deadpan']),
	e('grimacing', '1f62c', 'Grimacing face', ['awkward', 'oops', 'yikes', 'nervous']),
	e('sweat-smile', '1f605', 'Nervous laugh', ['nervous', 'phew', 'awkward', 'relief']),
	e('melting', '1fae0', 'Melting face', ['melting', 'hot', 'embarrassed', 'overwhelmed']),
	e('saluting', '1fae1', 'Saluting face', ['respect', 'yes sir', 'salute', 'ok']),
	e('yawning', '1f971', 'Yawning face', ['tired', 'bored', 'sleepy', 'boring']),
	e('sleeping', '1f634', 'Sleeping face', ['sleep', 'tired', 'rest', 'bored', 'night']),
	e('nerd', '1f913', 'Nerd face', ['nerd', 'smart', 'study', 'learn', 'geek']),
	// Mặt: buồn, giận, sợ
	e('pleading', '1f97a', 'Pleading face', ['please', 'sad', 'beg', 'cute']),
	e('cry', '1f622', 'Crying face', ['sad', 'cry', 'tear', 'upset']),
	e('sob', '1f62d', 'Sobbing face', ['sad', 'cry', 'devastated', 'tears']),
	e('pensive', '1f614', 'Pensive face', ['sad', 'regret', 'disappointed', 'thoughtful']),
	e('weary', '1f629', 'Weary face', ['tired', 'frustrated', 'exhausted', 'ugh']),
	e('scream', '1f631', 'Screaming in fear', ['scared', 'shock', 'horror', 'fear', 'omg']),
	e('fearful', '1f628', 'Fearful face', ['afraid', 'fear', 'worried', 'risk']),
	e('anxious', '1f630', 'Anxious face', ['anxious', 'stress', 'worried', 'nervous']),
	e('rage', '1f621', 'Angry face', ['angry', 'mad', 'furious', 'rage']),
	e('cursing', '1f92c', 'Cursing face', ['angry', 'swear', 'furious', 'rage']),
	e('steam', '1f624', 'Huffing face', ['frustrated', 'determined', 'angry', 'triumph']),
	e('dizzy', '1f635_200d_1f4ab', 'Dizzy face', ['confused', 'dizzy', 'overwhelmed']),
	e('nauseated', '1f922', 'Nauseated face', ['gross', 'sick', 'disgust', 'bad']),
	e('skull', '1f480', 'Skull', ['dead', 'lol', 'dying', 'danger', 'death']),
	e('clown', '1f921', 'Clown', ['fool', 'joke', 'silly', 'clown']),
	e('robot', '1f916', 'Robot', ['ai', 'robot', 'bot', 'automation', 'tech']),
	e('ghost', '1f47b', 'Ghost', ['ghost', 'spooky', 'ghosting', 'disappear']),
	e('alien', '1f47d', 'Alien', ['alien', 'weird', 'space', 'strange']),
	e('poop', '1f4a9', 'Pile of poo', ['bad', 'crap', 'funny', 'fail']),
	// Tay
	e('thumbs-up', '1f44d', 'Thumbs up', ['yes', 'good', 'like', 'approve', 'ok', 'agree']),
	e('thumbs-down', '1f44e', 'Thumbs down', ['no', 'bad', 'dislike', 'disagree']),
	e('clap', '1f44f', 'Clapping hands', ['applause', 'congrats', 'bravo', 'well done']),
	e('raised-hands', '1f64c', 'Raising hands', ['celebrate', 'yes', 'hooray', 'praise']),
	e('pray', '1f64f', 'Folded hands', ['please', 'thanks', 'pray', 'hope', 'grateful']),
	e('wave', '1f44b', 'Waving hand', ['hello', 'hi', 'bye', 'wave', 'greeting']),
	e('muscle', '1f4aa', 'Flexed biceps', ['strong', 'power', 'strength', 'gym', 'effort']),
	e('ok-hand', '1f44c', 'OK hand', ['ok', 'perfect', 'good', 'fine']),
	e('victory', '270c_fe0f', 'Victory hand', ['peace', 'victory', 'win', 'two']),
	e('crossed-fingers', '1f91e', 'Crossed fingers', ['luck', 'hope', 'wish', 'fingers crossed']),
	e('point-up', '261d_fe0f', 'Index pointing up', ['one', 'first', 'important', 'point', 'attention']),
	e('point-right', '1f449', 'Pointing right', ['this', 'next', 'right', 'point', 'look']),
	e('handshake', '1f91d', 'Handshake', ['deal', 'agreement', 'partner', 'team', 'trust']),
	e('writing-hand', '270d_fe0f', 'Writing hand', ['write', 'note', 'sign', 'plan']),
	e('fist', '1f44a', 'Fist bump', ['punch', 'bro', 'respect', 'hit']),
	e('palms-up', '1f932', 'Palms up', ['give', 'offer', 'please', 'open']),
	e('dancer', '1f483', 'Woman dancing', ['dance', 'party', 'celebrate', 'fun']),
	// Tim, lửa, năng lượng
	e('red-heart', '2764_fe0f', 'Red heart', ['love', 'heart', 'like', 'passion']),
	e('heart-fire', '2764_fe0f_200d_1f525', 'Heart on fire', ['passion', 'love', 'burning', 'desire']),
	e('broken-heart', '1f494', 'Broken heart', ['heartbreak', 'sad', 'breakup', 'loss']),
	e('sparkling-heart', '1f496', 'Sparkling heart', ['love', 'cute', 'sparkle', 'heart']),
	e('growing-heart', '1f497', 'Growing heart', ['love', 'growing', 'heart', 'excited']),
	e('fire', '1f525', 'Fire', ['fire', 'hot', 'lit', 'trending', 'burn', 'viral']),
	e('sparkles', '2728', 'Sparkles', ['magic', 'new', 'shiny', 'clean', 'special', 'ai']),
	e('star', '2b50', 'Star', ['star', 'favorite', 'rating', 'best']),
	e('glowing-star', '1f31f', 'Glowing star', ['star', 'shine', 'amazing', 'excellent']),
	e('collision', '1f4a5', 'Collision', ['boom', 'impact', 'explosion', 'crash', 'bang']),
	e('zap', '26a1', 'High voltage', ['energy', 'fast', 'power', 'electric', 'lightning']),
	e('hundred', '1f4af', 'Hundred points', ['100', 'perfect', 'score', 'totally', 'agree']),
	e('dizzy-star', '1f4ab', 'Dizzy', ['dizzy', 'star', 'magic', 'wow']),
	e('rainbow', '1f308', 'Rainbow', ['hope', 'happy', 'pride', 'colorful']),
	e('snowflake', '2744_fe0f', 'Snowflake', ['cold', 'winter', 'freeze', 'chill']),
	e('cloud-rain', '1f327_fe0f', 'Rain cloud', ['rain', 'sad', 'weather', 'gloomy']),
	e('volcano', '1f30b', 'Volcano', ['explosive', 'eruption', 'angry', 'hot']),
	e('globe', '1f30d', 'Globe', ['world', 'global', 'earth', 'international', 'planet']),
	e('plant', '1f331', 'Seedling', ['grow', 'growth', 'start', 'new', 'plant', 'seed']),
	// Ý tưởng, công việc, tiền
	e('light-bulb', '1f4a1', 'Light bulb', ['idea', 'insight', 'tip', 'smart', 'eureka', 'think']),
	e('rocket', '1f680', 'Rocket', ['launch', 'growth', 'fast', 'start', 'scale', 'boost']),
	e('target', '1f3af', 'Direct hit', ['goal', 'target', 'aim', 'focus', 'precise', 'bullseye']),
	e('trophy', '1f3c6', 'Trophy', ['win', 'winner', 'champion', 'award', 'success', 'best']),
	e('medal', '1f947', 'Gold medal', ['first', 'winner', 'gold', 'best', 'top']),
	e('crown', '1f451', 'Crown', ['king', 'queen', 'best', 'boss', 'royal']),
	e('gem', '1f48e', 'Gem', ['valuable', 'diamond', 'premium', 'rare', 'quality']),
	e('money-wings', '1f4b8', 'Money with wings', ['spend', 'expensive', 'cost', 'lose money', 'waste']),
	e('chart-up', '1f4c8', 'Chart increasing', ['growth', 'up', 'increase', 'trend', 'stocks', 'gain']),
	e('chart-down', '1f4c9', 'Chart decreasing', ['decline', 'down', 'loss', 'drop', 'crash']),
	e('bar-chart', '1f4ca', 'Bar chart', ['data', 'stats', 'report', 'analytics', 'numbers']),
	e('laptop', '1f4bb', 'Laptop', ['computer', 'work', 'code', 'online', 'tech']),
	e('bell', '1f514', 'Bell', ['notification', 'alert', 'subscribe', 'reminder']),
	e('megaphone', '1f4e3', 'Megaphone', ['announce', 'marketing', 'shout', 'promo', 'news']),
	e('books', '1f4da', 'Books', ['learn', 'study', 'read', 'knowledge', 'education']),
	e('graduation', '1f393', 'Graduation cap', ['graduate', 'school', 'education', 'degree', 'learn']),
	e('lock', '1f512', 'Locked', ['secure', 'private', 'lock', 'safe', 'closed']),
	e('gear', '2699_fe0f', 'Gear', ['settings', 'system', 'process', 'engineering', 'setup']),
	e('hammer-wrench', '1f6e0_fe0f', 'Hammer and wrench', ['tools', 'build', 'fix', 'repair']),
	e('brain', '1f9e0', 'Brain', ['brain', 'mind', 'smart', 'think', 'psychology', 'learn']),
	e('battery', '1f50b', 'Battery', ['energy', 'power', 'charge', 'full']),
	e('battery-low', '1faab', 'Low battery', ['tired', 'drained', 'low energy', 'exhausted']),
	e('gift', '1f381', 'Gift', ['gift', 'present', 'bonus', 'free', 'surprise']),
	e('balloon', '1f388', 'Balloon', ['party', 'birthday', 'celebrate', 'fun']),
	e('party-popper', '1f389', 'Party popper', ['party', 'celebrate', 'congrats', 'launch', 'tada']),
	e('confetti-ball', '1f38a', 'Confetti ball', ['celebrate', 'party', 'confetti', 'congrats']),
	e('bomb', '1f4a3', 'Bomb', ['bomb', 'explosive', 'danger', 'drop']),
	// Thời gian, dấu hiệu
	e('alarm-clock', '23f0', 'Alarm clock', ['time', 'alarm', 'deadline', 'wake up', 'morning', 'late']),
	e('hourglass', '23f3', 'Hourglass', ['time', 'wait', 'loading', 'patience', 'deadline']),
	e('check', '2705', 'Check mark', ['yes', 'done', 'correct', 'right', 'complete', 'success']),
	e('cross', '274c', 'Cross mark', ['no', 'wrong', 'mistake', 'fail', 'error', 'false']),
	e('warning', '26a0_fe0f', 'Warning', ['warning', 'caution', 'danger', 'risk', 'careful']),
	e('stop-sign', '1f6d1', 'Stop sign', ['stop', 'halt', 'end', 'wait']),
	e('question', '2753', 'Question mark', ['question', 'why', 'what', 'ask', 'unknown']),
	e('exclamation', '2757', 'Exclamation mark', ['important', 'alert', 'attention', 'note']),
	e('sos', '1f198', 'SOS', ['help', 'emergency', 'urgent']),
	e('new', '1f195', 'New', ['new', 'fresh', 'launch', 'update']),
	e('free', '1f193', 'Free', ['free', 'gratis', 'offer']),
	e('infinity', '267e_fe0f', 'Infinity', ['forever', 'infinite', 'unlimited', 'endless']),
	// Vật, con vật hay dùng
	e('coffee', '2615', 'Hot coffee', ['coffee', 'morning', 'break', 'energy']),
	e('pizza', '1f355', 'Pizza', ['food', 'pizza', 'party', 'hungry']),
	e('popcorn', '1f37f', 'Popcorn', ['watch', 'movie', 'drama', 'entertainment']),
	e('champagne', '1f37e', 'Champagne', ['celebrate', 'toast', 'success', 'party']),
	e('clinking-glasses', '1f942', 'Clinking glasses', ['cheers', 'toast', 'celebrate']),
	e('car', '1f697', 'Car', ['car', 'drive', 'travel', 'transport']),
	e('airplane', '2708_fe0f', 'Airplane', ['travel', 'flight', 'trip', 'fly']),
	e('house', '1f3e0', 'House', ['home', 'house', 'real estate', 'family']),
	e('camera-flash', '1f4f8', 'Camera with flash', ['photo', 'picture', 'camera', 'shoot']),
	e('dog', '1f415', 'Dog', ['dog', 'pet', 'puppy', 'loyal']),
	e('snail', '1f40c', 'Snail', ['slow', 'snail', 'lazy', 'patience']),
	e('turtle', '1f422', 'Turtle', ['slow', 'steady', 'patience']),
	e('snake', '1f40d', 'Snake', ['snake', 'danger', 'sneaky', 'fake']),
	e('shark', '1f988', 'Shark', ['shark', 'danger', 'aggressive', 'investor']),
];
